# Generated by Django 2.2.9 on 2020-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tanong_test',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
