# Generated by Django 2.2.9 on 2020-01-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_tanong_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tanong_test',
        ),
    ]
